### ISSUE TITLE
Can't compile due to missing assets 

### ISSUE THREAD

**Issue by dwmtz** [Plaristote/fallout-equestria-reloaded#1]
The following files are referenced in `qml.qrc`, but missing in the actual repository:

* `./assets/tilesets/metal.png `
* `./assets/tilesets/metal-walls.png `
* `./assets/backgrounds/ministry-of-peace.png` 
* `./assets/ui/ap-active.png `
* `./assets/ui/ap-inactive.png `
* `./assets/ui/cursors/target-tile.png `
* `./assets/ui/cursors/wait.png `
* `./assets/ui/button-pressed.png `
* `./assets/ui/button.png `
* `./assets/ui/PushButton.qml `
* `./assets/ui/WarningRectangle.qml`

**Comment by Plaristote** [comment]
Hi ! Sorry for the delay, I just noticed the issue, and pushed a commit that should fix it.

Most of these missing files are directly required by the engine, so I've added those. The tilesets, however, I took those away form `qml.qrc`. The thing is that this repository doesn't include all of the files I'm currently working with, as I would like to separate engine and game related data.

Note that you won't have a lot of resources available to check things out (tilesets, spritesheets, example levels won't be there).

Still, you should be able to make your own content using this repository, the Tiled editor, and the tutorial over there:
https://plaristote.github.io/fallout-equestria-reloaded
If you'd rather check things out with more assets and some examples of gameplay included, I'm pretty sure I'll be able to release a small demo by the end of December. By then, I'll have open another git repository to track the game data.

If you need anything else to get this thing running (or make content with it), I'll gladly lend a hand.

**Comment by Plaristote** [comment]
I just made sure everything was building and running properly from a fresh clone. I'm closing this.
